# Generated by Django 4.1.7 on 2023-03-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_time_creation_post_datecreation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_user',
            new_name='authorUser',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='time_creation',
            new_name='DateCreation',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_post',
            new_name='commentPost',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_user',
            new_name='commentUser',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category_choice',
            new_name='categoryType',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_category',
            new_name='postCategory',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating_post',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='author',
            name='rating_author',
        ),
        migrations.AddField(
            model_name='author',
            name='ratingAuthor',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=128),
        ),
    ]
