# Generated by Django 4.1.7 on 2023-03-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_author_user_author_authoruser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
